Rpc integration tests
bazed-editor/bazed pull request #46
Opened 2022-12-22 23:32 UTC by druskus20

This PR adds a couple of tests for the RPC API between the frontend and backend.
It won't scale, but it will make our life slightly easier while working on the RPC abstractions.

This relates to #34 but it's not high level enough

2022-12-23 23:02 UTC, buffet requested changes

2022-12-23 23:02 UTC, buffet commented on crates/bazed-rpc/src/server.rs
>  );
This should be

```
pub struct ClientSendHandle(pub UnboundedSender<ToFrontend>);
```

2022-12-26 18:15 UTC, druskus20 commented on crates/bazed-rpc/src/server.rs
>  );
done

2022-12-26 18:17 UTC, buffet approved these changes

2022-12-26 18:17 UTC, buffet requested changes
Please, conventional commits.

2022-12-26 18:22 UTC, buffet approved these changes

2022-12-26 18:23 UTC, merged