Start tauri-based frontend from main binary
bazed-editor/bazed pull request #99
Opened 2023-01-06 17:51 UTC by elkowar

This PR finally integrates tauri, and thus fixes #96.

2023-01-06 18:49 UTC, buffet requested changes
webkit2gtk-4.0 should really be libwebkit2gtk-4.0 for consistency

2023-01-06 18:49 UTC, buffet commented on crates/bazed-tauri/Cargo.toml
> -description = "A Tauri App"
This shouldn't be part of this commit.

2023-01-06 18:49 UTC, buffet commented on .github/workflows/ci.yaml
> +    #- uses: EmbarkStudios/cargo-deny-action@v1
This needs to be uncommented again.

2023-01-07 13:12 UTC, buffet approved these changes

2023-01-07 15:07 UTC, gwimm commented
```
   Compiling bazed-tauri v0.0.0 (C:\Users\Cpli\Documents\proto\bazed\crates\bazed-tauri)
error: failed to run custom build command for `bazed-tauri v0.0.0 (C:\Users\Cpli\Documents\proto\bazed\crates\bazed-tauri)`

Caused by:
  process didn't exit successfully: `C:\Users\Cpli\Documents\proto\bazed\target\debug\build\bazed-tauri-3c627ece64243281\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=C:\Users\Cpli\Documents\proto\bazed\crates\bazed-tauri/build.rs
  cargo:rerun-if-changed=C:\Users\Cpli\Documents\proto\bazed\crates\bazed-tauri/svelte/src
  cargo:rerun-if-changed=C:\Users\Cpli\Documents\proto\bazed\crates\bazed-tauri/svelte/package.json
  cargo:rerun-if-changed=C:\Users\Cpli\Documents\proto\bazed\crates\bazed-tauri/svelte/svelte.config.js

  --- stderr
  thread 'main' panicked at 'npm ci failed: Error { kind: NotFound, message: "program not found" }', crates\bazed-tauri\build.rs:13:10
```

2023-01-07 15:13 UTC, gwimm requested changes
see https://github.com/bazed-editor/bazed/pull/99#issuecomment-1374510139

2023-01-07 17:51 UTC, merged